

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OnlineBookingEntities : DbContext
{
    public OnlineBookingEntities()
        : base("name=OnlineBookingEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tm_Annotation> tm_Annotation { get; set; }

    public virtual DbSet<tm_Build> tm_Build { get; set; }

    public virtual DbSet<tm_Ext> tm_Ext { get; set; }

    public virtual DbSet<tm_ExtType> tm_ExtType { get; set; }

    public virtual DbSet<tm_Floor> tm_Floor { get; set; }

    public virtual DbSet<tm_ModelType> tm_ModelType { get; set; }

    public virtual DbSet<tm_Project> tm_Project { get; set; }

    public virtual DbSet<tm_Resource> tm_Resource { get; set; }

    public virtual DbSet<tm_UnitStatus> tm_UnitStatus { get; set; }

    public virtual DbSet<tm_WebImage> tm_WebImage { get; set; }

    public virtual DbSet<tr_ProjectBuild> tr_ProjectBuild { get; set; }

    public virtual DbSet<tr_ProjectBuildFloor> tr_ProjectBuildFloor { get; set; }

    public virtual DbSet<tr_ProjectModelType> tr_ProjectModelType { get; set; }

    public virtual DbSet<tr_ProjectResource> tr_ProjectResource { get; set; }

    public virtual DbSet<tm_UnitType> tm_UnitType { get; set; }

    public virtual DbSet<tm_BookingStatus> tm_BookingStatus { get; set; }

    public virtual DbSet<ts_Booking> ts_Booking { get; set; }

    public virtual DbSet<tm_Company> tm_Company { get; set; }

    public virtual DbSet<tm_OmiseChargeStatus> tm_OmiseChargeStatus { get; set; }

    public virtual DbSet<ts_Payment_Credit> ts_Payment_Credit { get; set; }

    public virtual DbSet<ts_Payment> ts_Payment { get; set; }

    public virtual DbSet<tr_ProjectGallery> tr_ProjectGallery { get; set; }

    public virtual DbSet<tr_ProjectGalleryResource> tr_ProjectGalleryResource { get; set; }

    public virtual DbSet<tr_ProjectSpecialPromotion> tr_ProjectSpecialPromotion { get; set; }

    public virtual DbSet<tr_UnitSpecialPromotion> tr_UnitSpecialPromotion { get; set; }

    public virtual DbSet<tr_ProjectBuildGroup> tr_ProjectBuildGroup { get; set; }

    public virtual DbSet<tm_ProjectConfig> tm_ProjectConfig { get; set; }

    public virtual DbSet<tr_Matrix_Config> tr_Matrix_Config { get; set; }

    public virtual DbSet<tm_Unit> tm_Unit { get; set; }

    public virtual DbSet<tr_ProjectRegisterQuota> tr_ProjectRegisterQuota { get; set; }

    public virtual DbSet<tm_Register> tm_Register { get; set; }

    public virtual DbSet<tr_UnitVIP> tr_UnitVIP { get; set; }

    public virtual DbSet<ts_Unitbooking_History> ts_Unitbooking_History { get; set; }

    public virtual DbSet<tr_ProjectTransferPayment> tr_ProjectTransferPayment { get; set; }

    public virtual DbSet<ts_Booking_VIP> ts_Booking_VIP { get; set; }

}

}

