
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tm_Build
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tm_Build()
    {

        this.tr_ProjectBuild = new HashSet<tr_ProjectBuild>();

        this.tr_ProjectBuildFloor = new HashSet<tr_ProjectBuildFloor>();

        this.tr_ProjectBuildGroup = new HashSet<tr_ProjectBuildGroup>();

        this.tr_ProjectBuildGroup1 = new HashSet<tr_ProjectBuildGroup>();

        this.tr_Matrix_Config = new HashSet<tr_Matrix_Config>();

        this.tm_Unit = new HashSet<tm_Unit>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public Nullable<bool> FlagActive { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectBuild> tr_ProjectBuild { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectBuildFloor> tr_ProjectBuildFloor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectBuildGroup> tr_ProjectBuildGroup { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectBuildGroup> tr_ProjectBuildGroup1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_Matrix_Config> tr_Matrix_Config { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tm_Unit> tm_Unit { get; set; }

}

}
