
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tm_Project
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tm_Project()
    {

        this.tr_ProjectBuild = new HashSet<tr_ProjectBuild>();

        this.tr_ProjectBuildFloor = new HashSet<tr_ProjectBuildFloor>();

        this.tr_ProjectModelType = new HashSet<tr_ProjectModelType>();

        this.tr_ProjectResource = new HashSet<tr_ProjectResource>();

        this.ts_Booking = new HashSet<ts_Booking>();

        this.tr_ProjectGallery = new HashSet<tr_ProjectGallery>();

        this.tr_ProjectSpecialPromotion = new HashSet<tr_ProjectSpecialPromotion>();

        this.tr_ProjectBuildGroup = new HashSet<tr_ProjectBuildGroup>();

        this.tm_ProjectConfig = new HashSet<tm_ProjectConfig>();

        this.tr_Matrix_Config = new HashSet<tr_Matrix_Config>();

        this.tm_Unit = new HashSet<tm_Unit>();

        this.tr_ProjectTransferPayment = new HashSet<tr_ProjectTransferPayment>();

        this.tr_ProjectRegisterQuota = new HashSet<tr_ProjectRegisterQuota>();

    }


    public System.Guid ID { get; set; }

    public string ProjectCode { get; set; }

    public string ProjectNameTH { get; set; }

    public string ProjectNameEN { get; set; }

    public string Location { get; set; }

    public string Vocation { get; set; }

    public Nullable<int> LineOrder { get; set; }

    public Nullable<bool> FlagActive { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public Nullable<int> BUID { get; set; }

    public Nullable<bool> IsOnlineBooking { get; set; }

    public Nullable<System.DateTime> TransferPaymentExpireDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectBuild> tr_ProjectBuild { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectBuildFloor> tr_ProjectBuildFloor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectModelType> tr_ProjectModelType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectResource> tr_ProjectResource { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ts_Booking> ts_Booking { get; set; }

    public virtual tm_Company tm_Company { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectGallery> tr_ProjectGallery { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectSpecialPromotion> tr_ProjectSpecialPromotion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectBuildGroup> tr_ProjectBuildGroup { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tm_ProjectConfig> tm_ProjectConfig { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_Matrix_Config> tr_Matrix_Config { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tm_Unit> tm_Unit { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectTransferPayment> tr_ProjectTransferPayment { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectRegisterQuota> tr_ProjectRegisterQuota { get; set; }

}

}
