
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tm_ProjectConfig
{

    public int ID { get; set; }

    public Nullable<System.Guid> ProjectID { get; set; }

    public Nullable<System.DateTime> CountDownDate { get; set; }

    public string CountDownTitle { get; set; }



    public virtual tm_Project tm_Project { get; set; }

}

}
