
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tm_Register
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tm_Register()
    {

        this.tr_ProjectRegisterQuota = new HashSet<tr_ProjectRegisterQuota>();

        this.ts_Booking = new HashSet<ts_Booking>();

        this.tr_ProjectTransferPayment = new HashSet<tr_ProjectTransferPayment>();

    }


    public System.Guid ID { get; set; }

    public Nullable<int> RegisterTypeID { get; set; }

    public string Code { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public string CitizenID { get; set; }

    public string Password { get; set; }

    public Nullable<bool> FlagActive { get; set; }

    public Nullable<System.DateTime> LastSignInDate { get; set; }

    public Nullable<System.DateTime> LastSignOutDate { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }

    public Nullable<System.DateTime> AllowBookDate { get; set; }



    public virtual tm_Ext tm_Ext { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectRegisterQuota> tr_ProjectRegisterQuota { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ts_Booking> ts_Booking { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectTransferPayment> tr_ProjectTransferPayment { get; set; }

}

}
