
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tm_Resource
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tm_Resource()
    {

        this.tm_WebImage = new HashSet<tm_WebImage>();

        this.tr_ProjectBuildFloor = new HashSet<tr_ProjectBuildFloor>();

        this.tr_ProjectModelType = new HashSet<tr_ProjectModelType>();

        this.tr_ProjectResource = new HashSet<tr_ProjectResource>();

        this.tr_ProjectGalleryResource = new HashSet<tr_ProjectGalleryResource>();

        this.tr_ProjectTransferPayment = new HashSet<tr_ProjectTransferPayment>();

    }


    public System.Guid ID { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string MimeType { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tm_WebImage> tm_WebImage { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectBuildFloor> tr_ProjectBuildFloor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectModelType> tr_ProjectModelType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectResource> tr_ProjectResource { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectGalleryResource> tr_ProjectGalleryResource { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectTransferPayment> tr_ProjectTransferPayment { get; set; }

}

}
