
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tr_ProjectTransferPayment
{

    public System.Guid ID { get; set; }

    public Nullable<System.Guid> ProjectID { get; set; }

    public Nullable<System.Guid> RegisterID { get; set; }

    public Nullable<System.Guid> ResourceID { get; set; }

    public Nullable<System.DateTime> TransferDate { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<decimal> ApproveAmount { get; set; }

    public Nullable<int> StatusID { get; set; }

    public Nullable<System.Guid> VerifyByID { get; set; }

    public Nullable<System.DateTime> VerifyDate { get; set; }

    public Nullable<int> Quota { get; set; }

    public Nullable<bool> FlagActive { get; set; }

    public Nullable<System.DateTime> CraeteDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }



    public virtual tm_Project tm_Project { get; set; }

    public virtual tm_Register tm_Register { get; set; }

    public virtual tm_Resource tm_Resource { get; set; }

}

}
