
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tr_ProjectQuota
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tr_ProjectQuota()
    {

        this.tr_ProjectRegisterQuota = new HashSet<tr_ProjectRegisterQuota>();

    }


    public int ID { get; set; }

    public Nullable<System.Guid> ProjectID { get; set; }

    public Nullable<int> Quota { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }

    public Nullable<int> LineOrder { get; set; }

    public Nullable<bool> FlagActive { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CraeteBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }

    public string Name { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tr_ProjectRegisterQuota> tr_ProjectRegisterQuota { get; set; }

}

}
