
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tr_ProjectGalleryResource
{

    public int ID { get; set; }

    public Nullable<int> ProjectGalleryID { get; set; }

    public Nullable<System.Guid> ResourceID { get; set; }

    public Nullable<int> LineOrder { get; set; }

    public Nullable<bool> FlagActie { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }



    public virtual tm_Resource tm_Resource { get; set; }

    public virtual tr_ProjectGallery tr_ProjectGallery { get; set; }

}

}
