
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ts_Booking
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ts_Booking()
    {

        this.ts_Payment = new HashSet<ts_Payment>();

        this.ts_Unitbooking_History = new HashSet<ts_Unitbooking_History>();

    }


    public System.Guid ID { get; set; }

    public Nullable<System.Guid> ProjectID { get; set; }

    public Nullable<System.Guid> UnitID { get; set; }

    public string BookingNumber { get; set; }

    public Nullable<decimal> BookingAmount { get; set; }

    public Nullable<decimal> SellingPrice { get; set; }

    public Nullable<System.Guid> CustomerID { get; set; }

    public string CustomerFirstName { get; set; }

    public string CustomerLastName { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerMobile { get; set; }

    public string CustomerCitizenID { get; set; }

    public Nullable<System.DateTime> BookingDate { get; set; }

    public Nullable<int> BookingStatusID { get; set; }

    public Nullable<System.DateTime> PaymentDueDate { get; set; }

    public Nullable<System.DateTime> CancelDate { get; set; }

    public Nullable<bool> FlagActive { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }

    public Nullable<decimal> SpecialPrice { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<System.DateTime> PaymentOverDueDate { get; set; }

    public Nullable<System.DateTime> UserUpdateDate { get; set; }

    public Nullable<System.Guid> UserUpdateByID { get; set; }

    public Nullable<decimal> ContractAmount { get; set; }



    public virtual tm_BookingStatus tm_BookingStatus { get; set; }

    public virtual tm_Project tm_Project { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ts_Payment> ts_Payment { get; set; }

    public virtual tm_Unit tm_Unit { get; set; }

    public virtual tm_Register tm_Register { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ts_Unitbooking_History> ts_Unitbooking_History { get; set; }

}

}
