
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ts_Booking_VIP
{

    public System.Guid ID { get; set; }

    public Nullable<System.Guid> ProjectID { get; set; }

    public Nullable<System.Guid> UnitID { get; set; }

    public Nullable<System.Guid> BookingID { get; set; }

    public string BookingNumber { get; set; }

    public Nullable<decimal> BookingAmount { get; set; }

    public Nullable<decimal> ContractAmount { get; set; }

    public Nullable<decimal> SellingPrice { get; set; }

    public Nullable<decimal> SpecialPrice { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<System.Guid> CustomerID { get; set; }

    public string CustomerFirstName { get; set; }

    public string CustomerLastName { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerMobile { get; set; }

    public string CustomerCitizen { get; set; }

    public Nullable<System.DateTime> BookingDate { get; set; }

    public int BookingStatusID { get; set; }

    public Nullable<System.DateTime> PaymentDueDate { get; set; }

    public Nullable<int> PaymentOverDueDate { get; set; }

    public Nullable<System.DateTime> CancelDate { get; set; }

    public bool FlagActive { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.Guid CreateBy { get; set; }

    public System.DateTime UpdateDate { get; set; }

    public System.Guid UpdateBy { get; set; }

    public Nullable<bool> IsSendMail { get; set; }

    public string UnitCode { get; set; }

    public string Email { get; set; }

}

}
