
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ts_Payment_Transfer
{

    public System.Guid ID { get; set; }

    public Nullable<System.Guid> PaymentID { get; set; }

    public Nullable<System.Guid> ResourceID { get; set; }

    public Nullable<System.DateTime> TransferDate { get; set; }

    public string Hours { get; set; }

    public string Minutes { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }



    public virtual tm_Resource tm_Resource { get; set; }

}

}
