
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ts_Payment_Credit
{

    public System.Guid ID { get; set; }

    public Nullable<System.Guid> PaymentID { get; set; }

    public string ChargeID { get; set; }

    public string IP { get; set; }

    public string Customer { get; set; }

    public Nullable<long> Refunded { get; set; }

    public Nullable<long> Amount { get; set; }

    public string Currency { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public string FailureCode { get; set; }

    public string FailureMessage { get; set; }

    public string OmiseTransaction { get; set; }

    public Nullable<bool> Paid { get; set; }

    public Nullable<bool> Reversed { get; set; }

    public Nullable<bool> Authorized { get; set; }

    public Nullable<bool> Capture { get; set; }

    public string ReturnURI { get; set; }

    public string CardFinancing { get; set; }

    public string CardBank { get; set; }

    public string CardFirstDigit { get; set; }

    public string CardLastDigit { get; set; }

    public string CardBrand { get; set; }

    public Nullable<int> CardExpirationMonth { get; set; }

    public Nullable<int> CardExpirationYear { get; set; }

    public string CardName { get; set; }

    public string AuthorizeURI { get; set; }

    public Nullable<bool> FlagActive { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<System.Guid> UpdateBy { get; set; }



    public virtual ts_Payment ts_Payment { get; set; }

}

}
