
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ts_Unitbooking_History
{

    public int ID { get; set; }

    public Nullable<System.Guid> UnitID { get; set; }

    public Nullable<int> UnitStatusID { get; set; }

    public Nullable<System.Guid> BookingID { get; set; }

    public Nullable<int> BookingStatusID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> CreateByID { get; set; }



    public virtual tm_BookingStatus tm_BookingStatus { get; set; }

    public virtual tm_Unit tm_Unit { get; set; }

    public virtual tm_UnitStatus tm_UnitStatus { get; set; }

    public virtual ts_Booking ts_Booking { get; set; }

}

}
