//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Booking.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tm_Project()
        {
            this.ts_Order = new HashSet<ts_Order>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BUID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectNameTH { get; set; }
        public string ProjectNameEN { get; set; }
        public string Location { get; set; }
        public string Vocation { get; set; }
        public Nullable<int> LineOrder { get; set; }
        public Nullable<bool> FlagActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
    
        public virtual tm_Company tm_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ts_Order> ts_Order { get; set; }
    }
}
