//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Booking.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ts_OrderPaymentMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ts_OrderPaymentMethod()
        {
            this.ts_OrderChagre = new HashSet<ts_OrderChagre>();
            this.ts_OrderPayment = new HashSet<ts_OrderPayment>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> MethodID { get; set; }
        public Nullable<bool> FlagActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ts_Order ts_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ts_OrderChagre> ts_OrderChagre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ts_OrderPayment> ts_OrderPayment { get; set; }
    }
}
