//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Booking.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ts_OrderPayment
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public Nullable<System.Guid> OrderPaymentMethodID { get; set; }
        public string OrderChargeID { get; set; }
        public string PaymentNo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsWebHookUpdate { get; set; }
        public Nullable<bool> FlagActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ts_OrderChagre ts_OrderChagre { get; set; }
        public virtual ts_Order ts_Order { get; set; }
        public virtual ts_OrderPaymentMethod ts_OrderPaymentMethod { get; set; }
    }
}
