//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Booking.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ts_OrderChagre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ts_OrderChagre()
        {
            this.ts_OrderPayment = new HashSet<ts_OrderPayment>();
        }
    
        public string id { get; set; }
        public Nullable<System.Guid> OrderPaymentMethodID { get; set; }
        public string @object { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string currency { get; set; }
        public string transaction_state { get; set; }
        public string status { get; set; }
        public string reference_order { get; set; }
        public string description { get; set; }
        public string redirect_url { get; set; }
        public string approval_code { get; set; }
        public string ref_1 { get; set; }
        public string ref_2 { get; set; }
        public string ref_3 { get; set; }
        public string failure_code { get; set; }
        public string failure_message { get; set; }
        public string source_id { get; set; }
        public string source_object { get; set; }
        public string source_brand { get; set; }
        public string source_issuer_bank { get; set; }
        public string source_card_masking { get; set; }
        public string created { get; set; }
        public Nullable<bool> IsWebHookUpdate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ts_OrderPayment> ts_OrderPayment { get; set; }
        public virtual ts_OrderPaymentMethod ts_OrderPaymentMethod { get; set; }
    }
}
